# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "pM6ttlTgkJPdZsZts5vDAs3nG4ovbZutVvMoCf53XrjUDsL847W+HOWUSo9aAU6gdl/K7Cg3cDWhdFBWF8a1ujCnr7AlYrRusNvksJwRaC4WqQO2K75iYS7cR1LRr4z107X8naCsyzXFVqWWZeIuYhyKaI63V3Y7RM6U5Ar47Eq+nfYf3ZoIK1Kts/w4UZeJsu44kFVY24ueS2bWWZ/lWKhgn6/LKzi4Ury1RRqvxPP246vvJ5CvxYL2yvz7JFbCnmIvF4MTzgbeEePuAC+owprRBNhBzse5UnuUBUrvfvEJCXccnn6dLlP05EidkCtVGUQdl0X+rpogVZwFZ+kFncEQIicc/c6GPxCCmCL/73k+TMH9GelJMmehCuuqx1H3B5LjtUaGjuxzUTBSt91BvScWdAKdw6BO8uAvq6svoixb8OxlxDwjgp9lterHIRaiA5hufOYZE1hcuMAN2jXtbgbCOqFxp9EKahR4zD0O8mcpKg+vqsPx6FEVUyPmnPHs3XNBSk38ohXvaJmHy2legDtklLLNPXRV3Jz5j02llmt6nUWG+kdXyk1krf7/QnDJAAA444ZgnrXHFa60eQxHYomV/jOf5dBu0IY3vKIH3gFRRGFqgEtlxl6WVpnNSnm7Waj9ZJiSZyVS4XrbYFWAOuRlpDDoe7upScwrGMnTBTA="


before_install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
