travis:
  secure:
    BINSTAR_TOKEN: pM6ttlTgkJPdZsZts5vDAs3nG4ovbZutVvMoCf53XrjUDsL847W+HOWUSo9aAU6gdl/K7Cg3cDWhdFBWF8a1ujCnr7AlYrRusNvksJwRaC4WqQO2K75iYS7cR1LRr4z107X8naCsyzXFVqWWZeIuYhyKaI63V3Y7RM6U5Ar47Eq+nfYf3ZoIK1Kts/w4UZeJsu44kFVY24ueS2bWWZ/lWKhgn6/LKzi4Ury1RRqvxPP246vvJ5CvxYL2yvz7JFbCnmIvF4MTzgbeEePuAC+owprRBNhBzse5UnuUBUrvfvEJCXccnn6dLlP05EidkCtVGUQdl0X+rpogVZwFZ+kFncEQIicc/c6GPxCCmCL/73k+TMH9GelJMmehCuuqx1H3B5LjtUaGjuxzUTBSt91BvScWdAKdw6BO8uAvq6svoixb8OxlxDwjgp9lterHIRaiA5hufOYZE1hcuMAN2jXtbgbCOqFxp9EKahR4zD0O8mcpKg+vqsPx6FEVUyPmnPHs3XNBSk38ohXvaJmHy2legDtklLLNPXRV3Jz5j02llmt6nUWG+kdXyk1krf7/QnDJAAA444ZgnrXHFa60eQxHYomV/jOf5dBu0IY3vKIH3gFRRGFqgEtlxl6WVpnNSnm7Waj9ZJiSZyVS4XrbYFWAOuRlpDDoe7upScwrGMnTBTA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
